theme: jekyll-theme-minimal
title: Practical Handbook for AI Experiements
description: This is a work-in-progress handbook for beginners/practitioners to conduct AI experiments with scientific rigor.
