theme: jekyll-theme-minimal
title: Practical Scientific Experimentation in AI/ML
description: This is a work-in-progress handbook for beginners/practitioners to conduct AI experiments with scientific rigor.
